image: harbor.eds.aphp.fr/public/python:3.8-slim

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - test
  - pages
  - package

Linting:
  stage: test
  cache:
    - key:
        files:
          - .pre-commit-config.yaml
      paths:
        - ~/.pre-commit
  before_script:
    - apt-get update
    - apt-get install -y --no-install-recommends git
    - pip install pre-commit
  script:
    - pre-commit run --all-files
  only:
    refs:
      - master
      - merge_request

Running Pytest:
  stage: test
  cache:
    - key:
        files:
          - poetry.lock
      paths:
        - .venv
  before_script:
    - pip install poetry
    - poetry run pip install cython setuptools # because `poetry install` does not correctly build the package
    - poetry install -v
  script:
    - poetry run pytest tests --cov edspdf_mupdf --junitxml=report.xml
  after_script:
    - poetry run coverage xml -o coverage.xml
  coverage: "/TOTAL.+ ([0-9]{1,3}%)/"
  artifacts:
    when: always
    paths:
      - coverage.xml
      - report.xml
      - ./
    reports:
      junit: report.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

  only:
    refs:
      - master
      - merge_request

Installation:
  stage: test
  script:
    - apt-get update
    - pip install .
  only:
    refs:
      - master
      - merge_request

Package:
  stage: package
  before_script:
    - pip install poetry
    - poetry config repositories.gitlab ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi
    - poetry config http-basic.gitlab gitlab-ci-token ${CI_JOB_TOKEN}
  script:
    - poetry publish --build -r gitlab
  only:
    - tags
