site_name: EDSPDF-MUPDF

repo_url: https://github.com/aphp/edspdf-mupdf

theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
  logo: assets/logo/edspdf-white.svg
  favicon: assets/logo/edspdf-blue.svg
  features:
    - navigation.tracking
    - navigation.instant
    - navigation.indexes
    - content.code.annotate

nav:
  - index.md

extra_css:
  - assets/stylesheets/extra.css
  - assets/termynal/termynal.css

extra_javascript:
  - https://cdn.jsdelivr.net/npm/vega@5
  - https://cdn.jsdelivr.net/npm/vega-lite@5
  - https://cdn.jsdelivr.net/npm/vega-embed@6
  - assets/termynal/termynal.js

watch:
  - edspdf_mupdf


extra:
  version:
    provider: mike

plugins:
  - search
  - autorefs:
      priority:
        - '*'
        - reference

  - mkdocstrings:
      enable_inventory: true
      custom_templates: docs/assets/templates
      handlers:
        python:
          import:
            - https://aphp.github.io/edspdf/latest/objects.inv
          options:
            docstring_style: numpy
            docstring_section_style: spacy
            heading_level: 2
            members_order: source
            show_root_toc_entry: false
            show_signature: false
            merge_init_into_class: true
  - glightbox:
      touchNavigation: true
      loop: false
      effect: none
      width: 100%
      height: auto
      zoomable: true
      draggable: true
  - bibtex:
      bibtex_file: "docs/references.bib"

  - mike

markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - footnotes
  - md_in_html
  - attr_list
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
